/* automatically generated by rust-bindgen 0.72.1 */

pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const KCW_Answer_KWC_OK: KCW_Answer = 0;
pub const KCW_Answer_KWC_NOT_OK: KCW_Answer = 1;
pub type KCW_Answer = ::std::os::raw::c_uint;
pub type KCW_Context = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    pub fn KCW_CreateContext(
        path: *const ::std::os::raw::c_char,
        result: *mut KCW_Context,
    ) -> KCW_Answer;
}
unsafe extern "C" {
    pub fn KCW_CreateContextFromPaths(
        path_particles: *const ::std::os::raw::c_char,
        path_interaction: *const ::std::os::raw::c_char,
        result: *mut KCW_Context,
    ) -> KCW_Answer;
}
unsafe extern "C" {
    pub fn KCW_DestroyContext(context: KCW_Context);
}
pub type KCW_Molecula = *mut ::std::os::raw::c_void;
pub type KCW_MoleculeDistribution = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KCW_MoleculaBuildParams {
    pub name: *const ::std::os::raw::c_char,
    pub anharmonic_spectrum: bool,
    pub rigid_rotator: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of KCW_MoleculaBuildParams"][::std::mem::size_of::<KCW_MoleculaBuildParams>() - 16usize];
    ["Alignment of KCW_MoleculaBuildParams"]
        [::std::mem::align_of::<KCW_MoleculaBuildParams>() - 8usize];
    ["Offset of field: KCW_MoleculaBuildParams::name"]
        [::std::mem::offset_of!(KCW_MoleculaBuildParams, name) - 0usize];
    ["Offset of field: KCW_MoleculaBuildParams::anharmonic_spectrum"]
        [::std::mem::offset_of!(KCW_MoleculaBuildParams, anharmonic_spectrum) - 8usize];
    ["Offset of field: KCW_MoleculaBuildParams::rigid_rotator"]
        [::std::mem::offset_of!(KCW_MoleculaBuildParams, rigid_rotator) - 9usize];
};
unsafe extern "C" {
    pub fn KCW_CreateMolecula(
        molecula_build: KCW_MoleculaBuildParams,
        context: *const ::std::os::raw::c_void,
        result: *mut KCW_Molecula,
    ) -> KCW_Answer;
}
unsafe extern "C" {
    pub fn KCW_DestroyMolecula(molecula: KCW_Molecula);
}
pub type KCW_Atom = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KCW_AtomBuildParams {
    pub name: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of KCW_AtomBuildParams"][::std::mem::size_of::<KCW_AtomBuildParams>() - 8usize];
    ["Alignment of KCW_AtomBuildParams"][::std::mem::align_of::<KCW_AtomBuildParams>() - 8usize];
    ["Offset of field: KCW_AtomBuildParams::name"]
        [::std::mem::offset_of!(KCW_AtomBuildParams, name) - 0usize];
};
unsafe extern "C" {
    pub fn KCW_CreateAtom(
        atom_build: KCW_AtomBuildParams,
        context: *const ::std::os::raw::c_void,
        result: *mut KCW_Atom,
    ) -> KCW_Answer;
}
unsafe extern "C" {
    pub fn KCW_DestroyAtom(atom: KCW_Atom);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KCW_AtomDistribution {
    pub energy: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of KCW_AtomDistribution"][::std::mem::size_of::<KCW_AtomDistribution>() - 8usize];
    ["Alignment of KCW_AtomDistribution"][::std::mem::align_of::<KCW_AtomDistribution>() - 8usize];
    ["Offset of field: KCW_AtomDistribution::energy"]
        [::std::mem::offset_of!(KCW_AtomDistribution, energy) - 0usize];
};
pub type KCW_Mixture = *mut ::std::os::raw::c_void;
pub type KCW_MixtureDistribution = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    pub fn KCW_CreateMixtureFromExists(
        molecules: *const KCW_Molecula,
        count_molecules: ::std::os::raw::c_ulong,
        atoms: *const KCW_Atom,
        count_atoms: ::std::os::raw::c_ulong,
        context: *const ::std::os::raw::c_void,
        result: *mut KCW_Mixture,
    ) -> KCW_Answer;
}
unsafe extern "C" {
    pub fn KCW_CreateMixture(
        molecules: *const KCW_MoleculaBuildParams,
        count_molecules: ::std::os::raw::c_ulong,
        atoms: *const KCW_AtomBuildParams,
        count_atoms: ::std::os::raw::c_ulong,
        context: *const ::std::os::raw::c_void,
        result: *mut KCW_Mixture,
    ) -> KCW_Answer;
}
unsafe extern "C" {
    pub fn KCW_DestroyMixture(mixture: KCW_Mixture);
}
unsafe extern "C" {
    pub fn KCW_MixtureCreateBoltzmanDistribution(
        mixture: KCW_Mixture,
        count: ::std::os::raw::c_ulong,
        T: *const f64,
        pressure: *const f64,
        n: *const *const f64,
        result: *mut KCW_MixtureDistribution,
    ) -> KCW_Answer;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KCW_CalculateParams {
    pub T: f64,
    pub p: f64,
    pub n: *const f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of KCW_CalculateParams"][::std::mem::size_of::<KCW_CalculateParams>() - 24usize];
    ["Alignment of KCW_CalculateParams"][::std::mem::align_of::<KCW_CalculateParams>() - 8usize];
    ["Offset of field: KCW_CalculateParams::T"]
        [::std::mem::offset_of!(KCW_CalculateParams, T) - 0usize];
    ["Offset of field: KCW_CalculateParams::p"]
        [::std::mem::offset_of!(KCW_CalculateParams, p) - 8usize];
    ["Offset of field: KCW_CalculateParams::n"]
        [::std::mem::offset_of!(KCW_CalculateParams, n) - 16usize];
};
unsafe extern "C" {
    pub fn KCW_MixtureCreateBoltzmanDistributionWithCallback(
        _mixture: KCW_Mixture,
        count: ::std::os::raw::c_ulong,
        Next: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> KCW_CalculateParams,
        >,
        state: *mut ::std::os::raw::c_void,
        result: *mut KCW_MixtureDistribution,
    ) -> KCW_Answer;
}
unsafe extern "C" {
    pub fn KCW_MixtureCreateBoltzmanDistributionFromOne(
        mixture: KCW_Mixture,
        T: f64,
        pressure: f64,
        n: *const f64,
        result: *mut KCW_MixtureDistribution,
    ) -> KCW_Answer;
}
unsafe extern "C" {
    pub fn KCW_DestroyMixtureDistribution(batch: KCW_MixtureDistribution);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KCW_TransportCoefficient {
    pub thermal_conductivity: f64,
    pub shear_viscosity: f64,
    pub bulk_viscosity: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of KCW_TransportCoefficient"]
        [::std::mem::size_of::<KCW_TransportCoefficient>() - 24usize];
    ["Alignment of KCW_TransportCoefficient"]
        [::std::mem::align_of::<KCW_TransportCoefficient>() - 8usize];
    ["Offset of field: KCW_TransportCoefficient::thermal_conductivity"]
        [::std::mem::offset_of!(KCW_TransportCoefficient, thermal_conductivity) - 0usize];
    ["Offset of field: KCW_TransportCoefficient::shear_viscosity"]
        [::std::mem::offset_of!(KCW_TransportCoefficient, shear_viscosity) - 8usize];
    ["Offset of field: KCW_TransportCoefficient::bulk_viscosity"]
        [::std::mem::offset_of!(KCW_TransportCoefficient, bulk_viscosity) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KCW_TransportCoefficientArray {
    pub data: *const KCW_TransportCoefficient,
    pub size: ::std::os::raw::c_ulong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of KCW_TransportCoefficientArray"]
        [::std::mem::size_of::<KCW_TransportCoefficientArray>() - 16usize];
    ["Alignment of KCW_TransportCoefficientArray"]
        [::std::mem::align_of::<KCW_TransportCoefficientArray>() - 8usize];
    ["Offset of field: KCW_TransportCoefficientArray::data"]
        [::std::mem::offset_of!(KCW_TransportCoefficientArray, data) - 0usize];
    ["Offset of field: KCW_TransportCoefficientArray::size"]
        [::std::mem::offset_of!(KCW_TransportCoefficientArray, size) - 8usize];
};
unsafe extern "C" {
    pub fn KCW_MixtureComputeTransportCoefficients(
        distribution: KCW_MixtureDistribution,
        n_electrons: *const f64,
        perturbation: *const f64,
        result: *mut KCW_TransportCoefficientArray,
    ) -> KCW_Answer;
}
unsafe extern "C" {
    pub fn KCW_MixtureComputeTransportCoefficientsFromOne(
        distribution: KCW_MixtureDistribution,
        n_electrons: f64,
        perturbation: f64,
        result: *mut KCW_TransportCoefficient,
    ) -> KCW_Answer;
}
unsafe extern "C" {
    pub fn KCW_DestroyTransportCoefficientArray(batch: KCW_TransportCoefficientArray);
}
