/* automatically generated by rust-bindgen 0.72.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub const KCW_Answer_KWC_OK: KCW_Answer = 0;
    pub const KCW_Answer_KWC_NOT_OK: KCW_Answer = 1;
    pub type KCW_Answer = ::std::os::raw::c_uint;
    pub type KCW_Context = *mut ::std::os::raw::c_void;
    unsafe extern "C" {
        #[link_name = "\u{1}_Z17KCW_CreateContextPKcPPv"]
        pub fn KCW_CreateContext(
            path: *const ::std::os::raw::c_char,
            result: *mut root::KCW_Context,
        ) -> root::KCW_Answer;
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z26KCW_CreateContextFromPathsPKcS0_PPv"]
        pub fn KCW_CreateContextFromPaths(
            path_particles: *const ::std::os::raw::c_char,
            path_interaction: *const ::std::os::raw::c_char,
            result: *mut root::KCW_Context,
        ) -> root::KCW_Answer;
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z18KCW_DestroyContextPv"]
        pub fn KCW_DestroyContext(context: root::KCW_Context);
    }
    pub type KCW_Molecula = *mut ::std::os::raw::c_void;
    pub type KCW_MoleculeDistribution = *mut ::std::os::raw::c_void;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct KCW_MoleculaBuildParams {
        pub name: *const ::std::os::raw::c_char,
        pub anharmonic_spectrum: bool,
        pub rigid_rotator: bool,
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z18KCW_CreateMolecula23KCW_MoleculaBuildParamsPKvPPv"]
        pub fn KCW_CreateMolecula(
            molecula_build: root::KCW_MoleculaBuildParams,
            context: *const ::std::os::raw::c_void,
            result: *mut root::KCW_Molecula,
        ) -> root::KCW_Answer;
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z19KCW_DestroyMoleculaPv"]
        pub fn KCW_DestroyMolecula(molecula: root::KCW_Molecula);
    }
    pub type KCW_Atom = *mut ::std::os::raw::c_void;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct KCW_AtomBuildParams {
        pub name: *const ::std::os::raw::c_char,
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z14KCW_CreateAtom19KCW_AtomBuildParamsPKvPPv"]
        pub fn KCW_CreateAtom(
            atom_build: root::KCW_AtomBuildParams,
            context: *const ::std::os::raw::c_void,
            result: *mut root::KCW_Atom,
        ) -> root::KCW_Answer;
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z15KCW_DestroyAtomPv"]
        pub fn KCW_DestroyAtom(atom: root::KCW_Atom);
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct KCW_AtomDistribution {
        pub energy: f64,
    }
    pub type KCW_Mixture = *mut ::std::os::raw::c_void;
    pub type KCW_MixtureDistribution = *mut ::std::os::raw::c_void;
    unsafe extern "C" {
        #[link_name = "\u{1}_Z27KCW_CreateMixtureFromExistsPKPvmS1_mPKvPS_"]
        pub fn KCW_CreateMixtureFromExists(
            molecules: *const root::KCW_Molecula,
            count_molecules: ::std::os::raw::c_ulong,
            atoms: *const root::KCW_Atom,
            count_atoms: ::std::os::raw::c_ulong,
            context: *const ::std::os::raw::c_void,
            result: *mut root::KCW_Mixture,
        ) -> root::KCW_Answer;
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z17KCW_CreateMixturePK23KCW_MoleculaBuildParamsmPK19KCW_AtomBuildParamsmPKvPPv"]
        pub fn KCW_CreateMixture(
            molecules: *const root::KCW_MoleculaBuildParams,
            count_molecules: ::std::os::raw::c_ulong,
            atoms: *const root::KCW_AtomBuildParams,
            count_atoms: ::std::os::raw::c_ulong,
            context: *const ::std::os::raw::c_void,
            result: *mut root::KCW_Mixture,
        ) -> root::KCW_Answer;
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z18KCW_DestroyMixturePv"]
        pub fn KCW_DestroyMixture(mixture: root::KCW_Mixture);
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z37KCW_MixtureCreateBoltzmanDistributionPvmPKdS1_PKS1_PS_"]
        pub fn KCW_MixtureCreateBoltzmanDistribution(
            mixture: root::KCW_Mixture,
            count: ::std::os::raw::c_ulong,
            T: *const f64,
            pressure: *const f64,
            n: *const *const f64,
            result: *mut root::KCW_MixtureDistribution,
        ) -> root::KCW_Answer;
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct KCW_CalculateParams {
        pub T: f64,
        pub p: f64,
        pub n: *const f64,
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z49KCW_MixtureCreateBoltzmanDistributionWithCallbackPvmPF19KCW_CalculateParamsS_ES_PS_"]
        pub fn KCW_MixtureCreateBoltzmanDistributionWithCallback(
            _mixture: root::KCW_Mixture,
            count: ::std::os::raw::c_ulong,
            Next: ::std::option::Option<
                unsafe extern "C" fn(
                    arg1: *mut ::std::os::raw::c_void,
                ) -> root::KCW_CalculateParams,
            >,
            state: *mut ::std::os::raw::c_void,
            result: *mut root::KCW_MixtureDistribution,
        ) -> root::KCW_Answer;
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z44KCW_MixtureCreateBoltzmanDistributionFromOnePvddPKdPS_"]
        pub fn KCW_MixtureCreateBoltzmanDistributionFromOne(
            mixture: root::KCW_Mixture,
            T: f64,
            pressure: f64,
            n: *const f64,
            result: *mut root::KCW_MixtureDistribution,
        ) -> root::KCW_Answer;
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z30KCW_DestroyMixtureDistributionPv"]
        pub fn KCW_DestroyMixtureDistribution(batch: root::KCW_MixtureDistribution);
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct KCW_TransportCoefficient {
        pub thermal_conductivity: f64,
        pub shear_viscosity: f64,
        pub bulk_viscosity: f64,
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct KCW_TransportCoefficientArray {
        pub data: *const root::KCW_TransportCoefficient,
        pub size: ::std::os::raw::c_ulong,
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z39KCW_MixtureComputeTransportCoefficientsPvPKdS1_P29KCW_TransportCoefficientArray"]
        pub fn KCW_MixtureComputeTransportCoefficients(
            distribution: root::KCW_MixtureDistribution,
            n_electrons: *const f64,
            perturbation: *const f64,
            result: *mut root::KCW_TransportCoefficientArray,
        ) -> root::KCW_Answer;
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z46KCW_MixtureComputeTransportCoefficientsFromOnePvddP24KCW_TransportCoefficient"]
        pub fn KCW_MixtureComputeTransportCoefficientsFromOne(
            distribution: root::KCW_MixtureDistribution,
            n_electrons: f64,
            perturbation: f64,
            result: *mut root::KCW_TransportCoefficient,
        ) -> root::KCW_Answer;
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z36KCW_DestroyTransportCoefficientArray29KCW_TransportCoefficientArray"]
        pub fn KCW_DestroyTransportCoefficientArray(batch: root::KCW_TransportCoefficientArray);
    }
}
