/* automatically generated by rust-bindgen 0.72.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    unsafe extern "C" {
        #[link_name = "\u{1}_Z8testcallf"]
        pub fn testcall(value: f32);
    }
    unsafe extern "C" {
        #[link_name = "\u{1}_Z1aPKc"]
        pub fn a(arg1: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
    }
}
